#!/bin/bash



echo "<>" > add.c

echo "<>" > addnode.c

echo "<>" > div.c

echo "<>" > execute.c

echo "<>" > free_stack.c

echo "<>" > main.c

echo "<>" > mod.c

echo "<>" > monty.h

echo "<>" > mul.c

echo "<>" > nop.c

echo "<>" > pall.c

echo "<>" > pchar.c

echo "<>" > pint.c

echo "<>" > pop.c

echo "<>" > pstr.c

echo "<>" > push.c

echo "<>" > queue.c

echo "<>" > rotl.c

echo "<>" > rotr.c

echo "<>" > stack.c

echo "<>" > sub.c

echo "<>" > swap.c



git add .

git commit -m "more update"

git push
