#!/bin/bash



mkdir bytecodes

cd bytecodes



echo "<>" > 00.m

echo "<>" > 06.m

echo "<>" > 07.m

echo "<>" > 09.m

echo "<>" > 12.m

echo "<>" > 19.m

echo "<>" > 28.m

echo "<>" > 31.m

echo "<>" > 35.m

echo "<>" > 47.m



git add .

git commit -m "initial commit"

git push
